import express from 'express';
import pg from 'pg';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const { Pool } = pg;
const app = express();
const port = Number(process.env.PORT) || 3000;
const databaseUrl = process.env.DATABASE_URL;
const projectDirectory = path.dirname(fileURLToPath(import.meta.url));
const serviceTables = { apache: 'apache_users', nginx: 'nginx_users' };

const pool = databaseUrl ? new Pool({
  connectionString: databaseUrl,
  ...(process.env.PGSSL === 'true' ? { ssl: { rejectUnauthorized: false } } : {})
}) : null;

const sampleUsers = {
  apache: [
    { name: 'ผู้ใช้ตัวอย่าง A', email: 'user.a@example.com', phone: '000-000-0001' },
    { name: 'ผู้ใช้ตัวอย่าง B', email: 'user.b@example.com', phone: '000-000-0002' },
    { name: 'ผู้ใช้ตัวอย่าง C', email: 'user.c@example.com', phone: '000-000-0003' },
    { name: 'นักศึกษาตัวอย่าง', email: 'student@example.com', phone: 'ไม่ระบุ', isStudent: true }
  ],
  nginx: [
    { name: 'ผู้ใช้ตัวอย่าง D', email: 'user.d@example.com', phone: '000-000-0004' },
    { name: 'ผู้ใช้ตัวอย่าง E', email: 'user.e@example.com', phone: '000-000-0005' },
    { name: 'ผู้ใช้ตัวอย่าง F', email: 'user.f@example.com', phone: '000-000-0006' },
    { name: 'นักศึกษาตัวอย่าง', email: 'student@example.com', phone: 'ไม่ระบุ', isStudent: true }
  ]
};

async function initializeDatabase() {
  for (const table of Object.values(serviceTables)) {
    await pool.query(`
      CREATE TABLE IF NOT EXISTS ${table} (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL,
        email TEXT NOT NULL,
        phone TEXT NOT NULL DEFAULT 'ไม่ระบุ',
        is_student BOOLEAN NOT NULL DEFAULT FALSE,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);
  }

  const { rows: legacyTable } = await pool.query("SELECT to_regclass('public.users') IS NOT NULL AS exists");
  if (legacyTable[0].exists) {
    for (const [service, table] of Object.entries(serviceTables)) {
      await pool.query(
        `INSERT INTO ${table} (id, name, email, phone, is_student, created_at)
         SELECT id, name, email, phone, is_student, created_at
         FROM users WHERE service = $1
         ON CONFLICT (id) DO NOTHING`,
        [service]
      );
      await pool.query(
        `SELECT setval(pg_get_serial_sequence($1, 'id'), COALESCE(MAX(id), 1), MAX(id) IS NOT NULL) FROM ${table}`,
        [`public.${table}`]
      );
    }
  }

  for (const [service, table] of Object.entries(serviceTables)) {
    const { rows } = await pool.query(`SELECT EXISTS (SELECT 1 FROM ${table}) AS has_users`);
    if (!rows[0].has_users) {
      for (const user of sampleUsers[service]) {
        await pool.query(
          `INSERT INTO ${table} (name, email, phone, is_student) VALUES ($1, $2, $3, $4)`,
          [user.name, user.email, user.phone, user.isStudent ?? false]
        );
      }
    }
  }
}

app.use(express.json({ limit: '20kb' }));

app.get('/api/health', async (_request, response) => {
  if (!pool) {
    response.status(503).json({ error: 'DATABASE_URL is not configured.' });
    return;
  }
  try {
    await pool.query('SELECT 1');
    response.json({ database: 'connected' });
  } catch {
    response.status(503).json({ database: 'unavailable' });
  }
});

app.get('/api/:service/users', async (request, response) => {
  const table = serviceTables[request.params.service];
  if (!table) {
    response.status(404).json({ error: 'Unknown service.' });
    return;
  }
  if (!pool) {
    response.status(503).json({ error: 'DATABASE_URL is not configured.' });
    return;
  }
  try {
    const { rows } = await pool.query(
      `SELECT id, name, email, phone, is_student AS "isStudent" FROM ${table} ORDER BY id DESC`
    );
    response.json(rows);
  } catch (error) {
    console.error('Could not load users:', error);
    response.status(500).json({ error: 'Could not load users from the database.' });
  }
});

app.post('/api/:service/users', async (request, response) => {
  const table = serviceTables[request.params.service];
  if (!table) {
    response.status(404).json({ error: 'Unknown service.' });
    return;
  }
  if (!pool) {
    response.status(503).json({ error: 'DATABASE_URL is not configured.' });
    return;
  }
  const { name, email, phone } = request.body ?? {};
  if (typeof name !== 'string' || !name.trim() ||
      typeof email !== 'string' || !email.trim() ||
      (phone !== undefined && typeof phone !== 'string')) {
    response.status(400).json({ error: 'A valid name and email are required.' });
    return;
  }

  try {
    const { rows } = await pool.query(
      `INSERT INTO ${table} (name, email, phone)
       VALUES ($1, $2, $3)
       RETURNING id, name, email, phone, is_student AS "isStudent"`,
      [name.trim(), email.trim(), phone?.trim() || 'ไม่ระบุ']
    );
    response.status(201).json(rows[0]);
  } catch (error) {
    console.error('Could not save user:', error);
    response.status(500).json({ error: 'Could not save user to the database.' });
  }
});

app.get(['/', '/apache', '/nginx'], (_request, response) => response.sendFile(path.join(projectDirectory, 'index.html')));
app.get('/app.js', (_request, response) => response.sendFile(path.join(projectDirectory, 'app.js')));
app.get('/styles.css', (_request, response) => response.sendFile(path.join(projectDirectory, 'styles.css')));

async function startServer() {
  if (pool) {
    try {
      await initializeDatabase();
    } catch (error) {
      console.error('Could not initialize PostgreSQL:', error);
    }
  }
  app.listen(port, () => console.log(`Server listening on port ${port}`));
}

startServer();