import express from 'express';
import pg from 'pg';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const { Pool } = pg;
const app = express();
const port = Number(process.env.PORT) || 3000;
const databaseUrl = process.env.DATABASE_URL;
const projectDirectory = path.dirname(fileURLToPath(import.meta.url));
const services = ['apache', 'nginx'];

const pool = databaseUrl ? new Pool({
  connectionString: databaseUrl,
  ...(process.env.PGSSL === 'true' ? { ssl: { rejectUnauthorized: false } } : {})
}) : null;

const sampleUsers = [
  { service: 'apache', name: 'ผู้ใช้ตัวอย่าง A', email: 'user.a@example.com', phone: '000-000-0001' },
  { service: 'apache', name: 'ผู้ใช้ตัวอย่าง B', email: 'user.b@example.com', phone: '000-000-0002' },
  { service: 'apache', name: 'ผู้ใช้ตัวอย่าง C', email: 'user.c@example.com', phone: '000-000-0003' },
  { service: 'apache', name: 'นักศึกษาตัวอย่าง', email: 'student@example.com', phone: 'ไม่ระบุ', isStudent: true },
  { service: 'nginx', name: 'ผู้ใช้ตัวอย่าง D', email: 'user.d@example.com', phone: '000-000-0004' },
  { service: 'nginx', name: 'ผู้ใช้ตัวอย่าง E', email: 'user.e@example.com', phone: '000-000-0005' },
  { service: 'nginx', name: 'ผู้ใช้ตัวอย่าง F', email: 'user.f@example.com', phone: '000-000-0006' },
  { service: 'nginx', name: 'นักศึกษาตัวอย่าง', email: 'student@example.com', phone: 'ไม่ระบุ', isStudent: true }
];

async function initializeDatabase() {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS users (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      service TEXT NOT NULL CHECK (service IN ('apache', 'nginx')),
      name TEXT NOT NULL,
      email TEXT NOT NULL,
      phone TEXT NOT NULL DEFAULT 'ไม่ระบุ',
      is_student BOOLEAN NOT NULL DEFAULT FALSE,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);

  const { rows } = await pool.query('SELECT EXISTS (SELECT 1 FROM users) AS has_users');
  if (!rows[0].has_users) {
    for (const user of sampleUsers) {
      await pool.query(
        'INSERT INTO users (service, name, email, phone, is_student) VALUES ($1, $2, $3, $4, $5)',
        [user.service, user.name, user.email, user.phone, user.isStudent ?? false]
      );
    }
  }
}

app.use(express.json({ limit: '20kb' }));

app.get('/api/health', async (_request, response) => {
  if (!pool) {
    response.status(503).json({ error: 'DATABASE_URL is not configured.' });
    return;
  }
  try {
    await pool.query('SELECT 1');
    response.json({ database: 'connected' });
  } catch {
    response.status(503).json({ database: 'unavailable' });
  }
});

app.get('/api/users', async (_request, response) => {
  if (!pool) {
    response.status(503).json({ error: 'DATABASE_URL is not configured.' });
    return;
  }
  try {
    const { rows } = await pool.query(
      'SELECT id, service, name, email, phone, is_student AS "isStudent" FROM users ORDER BY id DESC'
    );
    response.json({
      apache: rows.filter((user) => user.service === 'apache'),
      nginx: rows.filter((user) => user.service === 'nginx')
    });
  } catch (error) {
    console.error('Could not load users:', error);
    response.status(500).json({ error: 'Could not load users from the database.' });
  }
});

app.post('/api/users', async (request, response) => {
  if (!pool) {
    response.status(503).json({ error: 'DATABASE_URL is not configured.' });
    return;
  }
  const { service, name, email, phone } = request.body ?? {};
  if (!services.includes(service) || typeof name !== 'string' || !name.trim() ||
      typeof email !== 'string' || !email.trim() ||
      (phone !== undefined && typeof phone !== 'string')) {
    response.status(400).json({ error: 'A valid service, name, and email are required.' });
    return;
  }

  try {
    const { rows } = await pool.query(
      `INSERT INTO users (service, name, email, phone)
       VALUES ($1, $2, $3, $4)
       RETURNING id, name, email, phone, is_student AS "isStudent"`,
      [service, name.trim(), email.trim(), phone?.trim() || 'ไม่ระบุ']
    );
    response.status(201).json(rows[0]);
  } catch (error) {
    console.error('Could not save user:', error);
    response.status(500).json({ error: 'Could not save user to the database.' });
  }
});

app.get('/', (_request, response) => response.sendFile(path.join(projectDirectory, 'index.html')));
app.get('/app.js', (_request, response) => response.sendFile(path.join(projectDirectory, 'app.js')));
app.get('/styles.css', (_request, response) => response.sendFile(path.join(projectDirectory, 'styles.css')));

if (pool) {
  initializeDatabase().catch((error) => {
    console.error('Could not initialize PostgreSQL:', error);
  });
}

app.listen(port, () => console.log(`Server listening on port ${port}`));